# Generated by Django 6.0.3 on 2026-05-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
