# Generated by Django 6.0.3 on 2026-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0002_rename_firstname_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
